# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Brandon Jenniges
email: brandon.jenniges@icloud.com
url: https://brandonjenniges.me
permalink: /:title/
author: Brandon Jenniges
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2016 Brandon Jenniges.'
credits: ' This site was created using a free to use, open source Jekyll theme called <a href="https://github.com/swcool/landing-page-theme">Landing Page</a> as a reference.'


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/steveholt55
  - title: linkedin
    url: http://linkedin.com/in/bjenniges
  - title: stack-overflow
    url: http://stackoverflow.com/users/1922313/brandon
  - title: twitter
    url: http://twitter.com/steveholt55

# ----------------------- #
#   Build Settings        #
# ----------------------- #

collections:
 projects:
  output: true


defaults:
   -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"