# Site settings
title: Brandon Jenniges
email: brandon.jenniges@icloud.com
url: https://brandon-asahi.com
permalink: /:title/
baseurl: /brandon

#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0b61a4 #80B3FF
  secondary: 033e6b #FD6E8A
  secondary-dark: 36454F #A2122F

# Footer settings
footer:
  copyright: Brandon Jenniges
  location: Location
  social: Social
  contact: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/pub/brandon-jenniges/58/a4a/9b9
  - title: twitter
    url: http://twitter.com/steveholt55
  - title: stack-overflow
    url: http://stackoverflow.com/users/1922313/brandon
  - title: github
    url: https://github.com/steveholt55

# Postal address (add as many lines as necessary)
address:
  - line: Minneapolis, MN

# Credits content
contact: '<a href="mailto:brandon.jenniges@icloud.com">brandon.jenniges@icloud.com</a>'

# Build settings
markdown: redcarpet

collections:
 portfolio:
  output: true  


defaults:
   -
    scope:
      path: ""
      type: "portfolio"
    values:
      layout: "project"